version: '3.8'
services:
    mysql:
      container_name: mysql
#      hostname: test
      image: mysql:latest
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: ismat
        MYSQL_PASSWORD: secret
      volumes:
        - db:/var/lib/mysql
      ports:
        - "3306:3306"


    postgres:
      image: postgres:latest
      restart: always
      ports:
        - "5432:5432"
      environment:
        #        POSTGRES_DB: postgresql
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
      volumes:
        - dbp:/var/lib/postgres/data
#      networks:
#        - custom-network


#    myapp:
#     image: msstudent:v22
#     ports:
#       - '8088:8088'
##     networks:
##       - custom-network
#     depends_on:
#       - postgres
#     environment:
#       HOST : postgres
#       PORT : 5432



volumes:
  db:
  dbp:

#networks:
#  custom-network: